sudo: required
language: node_js
node_js:
  - node
python:
  - "3.7"

install:
  - npm install
script: npm run test

after_success:
  - ./login.sh
  - echo "$DockerPassword" | docker login --username "$DockerUsername" --password-stdin; docker build . -t blzface/future-of-security-frontend
  - echo "$DockerPassword" | docker login --username "$DockerUsername" --password-stdin; docker push blzface/future-of-security-frontend
