sudo: required
language: node_js
node_js:
  - node

after_success:
  - ./login.sh
  - echo "$DockerPassword" | docker login --username "$DockerUsername" --password-stdin; docker build . -t blzface/future-of-security-frontend
  - echo "$DockerPassword" | docker login --username "$DockerUsername" --password-stdin; docker push blzface/future-of-security-frontend
