sudo: required
language: node_js
node_js:
  - node
python:
  - "3.7"

before_install:
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U virtualenvwrapper
  - python3 -V
  - pip3 -V
install:
  - npm install
script: npm run test

after_success:
  - ./login.sh
  - echo "$DockerPassword" | docker login --username "$DockerUsername" --password-stdin; docker build . -t blzface/future-of-security-frontend
  - echo "$DockerPassword" | docker login --username "$DockerUsername" --password-stdin; docker push blzface/future-of-security-frontend
